"""an event carries the id the device gave it

Adds event.client_uuid so recording an event is idempotent - see the field
outbox in frontend/field/app.js and the column's comment in models.py.
Nullable and additive: every event already on a farm keeps its NULL, and a
unique index over a nullable column lets SQLite hold as many of those as
there are.

Revision ID: 94ab18b9e9c1
Revises: 063aa8282327
Created: 2026-09-08 13:51:06.980626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - autogenerate renders sqlmodel.sql.sqltypes.AutoString


revision = '94ab18b9e9c1'
down_revision = '063aa8282327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_client_uuid'), ['client_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_client_uuid'))
        batch_op.drop_column('client_uuid')

    # ### end Alembic commands ###
